version: 2

jobs:
  build_test_deploy:
    docker:
      - image: circleci/node:10.15.2
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "e3:86:1f:21:1d:36:98:b4:d0:cd:be:00:47:9b:cf:7b"
      - run: npm run deploy

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build_test_deploy:
            filters:
              branches:
                ignore: gh-pages
